### ISSUE TITLE
Create Contributing guidelines

### ISSUE THREAD

**Issue by LuluNwenyi** [writewithocto/octo#146]
Hi @voraciousdev 
Since it’s Hacktoberfest period, for new contributors, it would be nice to have a CONTRIBUTING.md file with guidelines and instructions on how to navigate the repo and contribute. If this is a thing I could work on, I’d love to be assigned to this.

**Comment by voraciousdev** [comment]
Hey @LuluNwenyi! This is a great idea, and I'll do my best to get one started in the next couple of days using [this template](https://github.com/nayafia/contributing-template). Thanks so much for bringing this up!
