### ISSUE TITLE
Does not support Korean language

### ISSUE THREAD

**Issue by pokedexter** [writewithocto/octo#159]
Expected behavior:

> 다람쥐 헛 쳇바퀴에 타고파.

Actual rendering:

> ㄷ다라람ㅈ쥐 ㅎ헛 ㅊ쳇ㅂ바쿠퀴에에 타고고파파.

By typing characters one by one in Korean, the text get broken like this.

**Comment by voraciousdev** [comment]
Hey @pokedexter! I'd love to dig into this, but I think I'm going to struggle with reproducing this on my end. Any chance you could help me out with getting a reproducible example set up?

**Comment by pokedexter** [comment]
You will have to change the keyboard IME language to korean with understanding the language itself. It seems like I should solve this myself.

https://v3.vuejs.org/guide/forms.html#basic-usage

> For languages that require an IME (opens new window)(Chinese, Japanese, Korean etc.), you'll notice that v-model doesn't get updated during IME composition. If you want to respond to these updates as well, use an input event listener and value binding instead of using v-model.

Almost solved (but not completely) by changing Ink component:

Before:

`<Ink ref="editor" v-model="markdown" :appearance="appearance" :settings="{ images: { enabled: true } }" class="editor" />`

After:

`<Ink ref="editor" :value="markdown" :appearance="appearance" :settings="{ images: { enabled: true } }" class="editor" />`

Before: 
> ㄷ다라람ㅈ쥐 ㅎ헛 ㅊ쳇ㅂ바쿠퀴에에 타고고파파.
After:
> ㄷ다람쥐 헌 쳇바퀴에 타고파.

Still has issue on first character input, but solved most of the problem.

**Comment by voraciousdev** [comment]
@pokedexter do you know if there is an open issue on CodeMirror for this? If so, could you please link it?

**Comment by voraciousdev** [comment]
Hey @pokedexter, is there any chance you could try this again in Octo? I just updated all of the CodeMirror dependencies yesterday, and it fixed a similar issue with Japanese characters.

**Comment by pokedexter** [comment]
Looks like it is fixed.

**Comment by voraciousdev** [comment]
@pokedexter that's great news! Thanks so much for verifying!
