### ISSUE TITLE
Strikethrough applied to text b/w tildes 

### ISSUE THREAD

**Issue by rcmoret** [writewithocto/octo#63]
I think this would be a nice improvement:

Basically if you have
> \~some outdated text~
Then it would render with a strikethrough applied
> ~ ~some outdated text~ ~ #  I can get it render exactly like it would in the app, but that's the idea.

**Comment by voraciousdev** [comment]
We currently have strikethrough support by using 2 tildes on each side (e.g. `~~this text is crossed out~~`), but it looks like it _should_ support strikethrough with only 1 tilde on each side.

**Comment by voraciousdev** [comment]
It turns out strikethrough with only a single `~` is non-standard Markdown. For now, we are just going to support it with `~~`.
