### ISSUE TITLE
Easy daily notes

### ISSUE THREAD

**Issue by keller00** [writewithocto/octo#95]
Hi, love your app! 😄 

I'd like to ask for a feature, where Octo could open a daily note with a click of a button.
Maybe default  markdown could have the current date as title and it could add a default tag to end of the note.
So something similar to:

```md
# current_date

<default cursor position>

#user_defined_parent_tag_if_set
```

**Comment by voraciousdev** [comment]
Hey @keller00! Thank you! This is definitely an interesting idea. Is the goal to have a link on the sidebar open the same note throughout the day and then replace it with a new note at the start of every day? If not, could you provide some more context? I like the idea, and even if it doesn't become a core feature, I think this absolutely needs to be an extension at minimum!

**Comment by keller00** [comment]
> Hey @keller00! Thank you! This is definitely an interesting idea. Is the goal to have a link on the sidebar open the same note throughout the day and then replace it with a new note at the start of every day? If not, could you provide some more context? I like the idea, and even if it doesn't become a core feature, I think this absolutely needs to be an extension at minimum!

No, that's it exactly! :)
